SET SERVEROUTPUT ON;

DROP TABLE UTILIZATOR;
--- TABELA USER
CREATE TABLE UTILIZATOR (
    ID  NUMBER(10)  NOT NULL,
    EMAIL VARCHAR2(20) NOT NULL,
    PASSWORD VARCHAR2(50) NOT NULL,
    ADMIN VARCHAR2(1) DEFAULT '0' NOT NULL
);

ALTER TABLE UTILIZATOR ADD (CONSTRAINT user_pk PRIMARY KEY (ID));

CREATE SEQUENCE user_seq START WITH 1;

--- TRIGER PENTRU AUTOINCREMENT ID
CREATE OR REPLACE TRIGGER AUTOINCREMENT_USER 
BEFORE INSERT ON UTILIZATOR 
FOR EACH ROW
BEGIN
    SELECT user_seq.NEXTVAL INTO :new.id FROM dual;
END;


--------------------------------------

--- REGISTER
CREATE OR REPLACE FUNCTION REGISTER (EMAIL_USER IN VARCHAR2, PASSWORD IN VARCHAR2) RETURN NUMBER AS
    ID_CHECK NUMBER := 0;
BEGIN   
    SELECT COUNT(ID) INTO ID_CHECK FROM UTILIZATOR WHERE EMAIL = EMAIL_USER;
    
    IF ID_CHECK = 0 THEN 
        INSERT INTO UTILIZATOR(EMAIL, PASSWORD) VALUES (EMAIL_USER, ORA_HASH(PASSWORD));
        RETURN 1;
    END IF;
    
    RETURN 0;
END;


--- LOGIN
CREATE OR REPLACE FUNCTION LOGIN (EMAIL_USER IN VARCHAR2, PASSWORD_USER IN VARCHAR2) RETURN NUMBER AS
    CNT NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO CNT FROM UTILIZATOR WHERE EMAIL = EMAIL_USER AND PASSWORD = ORA_HASH(PASSWORD_USER);
    IF CNT = 0 THEN
        RETURN 0;
    END IF;
    
    RETURN 1;
END;
/
